import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const jura = localFont({
	src: "./fonts/Jura-VariableFont_wght.ttf",
	variable: "--font-jura",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en-us">
			<body className={jura.variable}>
				<main>{children}</main>
			</body>
		</html>
	);
}
